In [6]:
import numpy as np

In [9]:
np.__version__

'2.3.4'

In [7]:
np.__doc__

'\nNumPy\n=====\n\nProvides\n  1. An array object of arbitrary homogeneous items\n  2. Fast mathematical operations over arrays\n  3. Linear Algebra, Fourier Transforms, Random Number Generation\n\nHow to use the documentation\n----------------------------\nDocumentation is available in two forms: docstrings provided\nwith the code, and a loose standing reference guide, available from\n`the NumPy homepage <https://numpy.org>`_.\n\nWe recommend exploring the docstrings using\n`IPython <https://ipython.org>`_, an advanced Python shell with\nTAB-completion and introspection capabilities.  See below for further\ninstructions.\n\nThe docstring examples assume that `numpy` has been imported as ``np``::\n\n  >>> import numpy as np\n\nCode snippets are indicated by three greater-than signs::\n\n  >>> x = 42\n  >>> x = x + 1\n\nUse the built-in ``help`` function to view a function\'s docstring::\n\n  >>> help(np.sort)\n  ... # doctest: +SKIP\n\nFor some objects, ``np.info(obj)`` may provide add

In [8]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [12]:
arr = np.array([3, 4, 5])
arr, type(arr)

(array([3, 4, 5]), numpy.ndarray)

In [14]:
arr = np.array([3, 4, 5])
print(arr, type(arr), arr.dtype)

[3 4 5] <class 'numpy.ndarray'> int64


In [15]:
arr = np.array([3, 4, 5, 6.31])
print(arr, type(arr), arr.dtype)

[3.   4.   5.   6.31] <class 'numpy.ndarray'> float64


In [17]:
arr = np.array([3, 4, 5, 6.31, "hello"])
print(arr, type(arr), arr.dtype, type(arr[0]))

['3' '4' '5' '6.31' 'hello'] <class 'numpy.ndarray'> <U32 <class 'numpy.str_'>


In [18]:
arr = np.array([3, 4, 5, 6.31, "hello", [312, 41]])
print(arr, type(arr), arr.dtype, type(arr[0]))

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (6,) + inhomogeneous part.

In [19]:
arr = np.array([ [4, 5, 6.31], ["hello", 312, 41]])
print(arr, type(arr), arr.dtype, type(arr[0]))

[['4' '5' '6.31']
 ['hello' '312' '41']] <class 'numpy.ndarray'> <U32 <class 'numpy.ndarray'>


In [21]:
arr = np.array([ [4, 5, 6.31, 321], ["hello", 312, 41, 321]])
print(arr, type(arr), arr.dtype, type(arr[0]))

[['4' '5' '6.31' '321']
 ['hello' '312' '41' '321']] <class 'numpy.ndarray'> <U32 <class 'numpy.ndarray'>


In [23]:
arr = np.array([ [1, 2, 3], [4, 5, 6]])
print(arr, type(arr), arr.dtype, type(arr[0]))
print(arr.shape)

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> int64 <class 'numpy.ndarray'>
(2, 3)


In [24]:
arr = np.array([ [1, 2, 3], [4, 5, 6]], dtype=np.int8)

In [27]:
bin(0), bin(1), bin(2)

('0b0', '0b1', '0b10')

In [28]:
for i in range(17):
    print("i=", i,  " in binar:", bin(i))

i= 0  in binar: 0b0
i= 1  in binar: 0b1
i= 2  in binar: 0b10
i= 3  in binar: 0b11
i= 4  in binar: 0b100
i= 5  in binar: 0b101
i= 6  in binar: 0b110
i= 7  in binar: 0b111
i= 8  in binar: 0b1000
i= 9  in binar: 0b1001
i= 10  in binar: 0b1010
i= 11  in binar: 0b1011
i= 12  in binar: 0b1100
i= 13  in binar: 0b1101
i= 14  in binar: 0b1110
i= 15  in binar: 0b1111
i= 16  in binar: 0b10000


In [30]:
2 ** 4 - 1

15

# uint8 este de la 0 la 255

In [34]:
arr = np.array([ [1, 2, 3], [4, 255, 6]], dtype=np.uint8)

# uint8 este la -128 la 127

In [36]:
arr = np.array([ [1, 2, 3], [4, 127, 6]], dtype=np.int8)

In [38]:
arr = np.array([ [1, 2, 3], [4, -128, 6]], dtype=np.int8)

In [31]:
2 ** 8 - 1

255

# Fast mathematical operations over arrays

In [39]:
arr = np.array([123, 312, 4, 32, 31])
arr

array([123, 312,   4,  32,  31])

In [40]:
arr + 2

array([125, 314,   6,  34,  33])

In [41]:
arr * 2

array([246, 624,   8,  64,  62])

In [42]:
arr + arr 

array([246, 624,   8,  64,  62])

In [43]:
arr - arr 

array([0, 0, 0, 0, 0])

In [44]:
arr = np.array([31, 321, 32])
arr

array([ 31, 321,  32])

In [45]:
arr = np.array(range(12))
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
arr = np.arange(12, dtype=np.float64)
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [49]:
arr = np.arange(12,32)
arr

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31])

In [50]:
arr > 20

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [51]:
arr[arr > 20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [52]:
arr % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [53]:
arr[ (arr > 20) & (arr % 2 == 0)]

array([22, 24, 26, 28, 30])

In [54]:
np.random.randint(0, 10)

2

In [59]:
np.random.randint(0, 10, 20)

array([5, 7, 8, 0, 0, 0, 1, 0, 9, 1, 0, 4, 1, 9, 2, 9, 0, 9, 3, 6])

In [60]:
np.random.randint(0, 10, (2, 3))

array([[0, 1, 8],
       [3, 6, 2]])

In [61]:
np.random.randint(0, 10, (5, 10))

array([[1, 6, 3, 1, 8, 3, 9, 3, 1, 7],
       [6, 4, 5, 3, 0, 5, 5, 4, 1, 1],
       [4, 2, 6, 7, 8, 6, 4, 9, 9, 3],
       [3, 8, 0, 0, 4, 4, 3, 6, 1, 7],
       [9, 0, 6, 3, 3, 0, 7, 2, 9, 0]])