In [8]:
import numpy as np
import matplotlib.pyplot  as plt
from sklearn.model_selection import train_test_split


In [9]:
x = np.arange(1, 11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
x[:2], x[2:]

(array([1, 2]), array([ 3,  4,  5,  6,  7,  8,  9, 10]))

In [11]:
train_test_split(x)

[array([2, 4, 7, 6, 3, 1, 9]), array([ 8,  5, 10])]

In [15]:
train_test_split(x)

[array([ 2,  8,  6,  3, 10,  4,  9]), array([7, 1, 5])]

In [17]:
x = np.arange(1, 11)
y = 2 * x + 1
print(x)
print(y)

[ 1  2  3  4  5  6  7  8  9 10]
[ 3  5  7  9 11 13 15 17 19 21]


In [18]:
train_test_split(x, y)

[array([ 6,  1,  3,  5,  2,  4, 10]),
 array([7, 9, 8]),
 array([13,  3,  7, 11,  5,  9, 21]),
 array([15, 19, 17])]

In [19]:
train_test_split(x, y, test_size=0.2)

[array([ 7,  2,  3,  5,  4, 10,  1,  8]),
 array([9, 6]),
 array([15,  5,  7, 11,  9, 21,  3, 17]),
 array([19, 13])]

In [32]:
train_test_split(x, y, test_size=0.2, random_state=42)

[array([ 6,  1,  8,  3, 10,  5,  4,  7]),
 array([9, 2]),
 array([13,  3, 17,  7, 21, 11,  9, 15]),
 array([19,  5])]